# Generated by Codex on 2026-05-21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="部门名称")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80, verbose_name="分类名称")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="projects.department",
                        verbose_name="所属部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目类型",
                "verbose_name_plural": "项目类型",
                "ordering": ["sort_order", "created_at"],
                "unique_together": {("name", "department")},
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("host", models.SlugField(max_length=120, unique=True, verbose_name="主机名")),
                ("name", models.CharField(max_length=120, verbose_name="项目名称")),
                (
                    "template",
                    models.CharField(
                        choices=[("pc", "PC端"), ("mobile", "手机端")],
                        max_length=20,
                        verbose_name="模板",
                    ),
                ),
                ("description", models.TextField(verbose_name="项目描述")),
                ("prompt", models.TextField(blank=True, verbose_name="用户提示词")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.projectcategory",
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.department",
                        verbose_name="所属部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
