# Generated by Codex on 2026-05-25

from datetime import datetime

from django.db import migrations
from django.utils import timezone


DEPARTMENTS = [
    (1, "产品研发中心", 10),
    (2, "教研中心", 20),
    (3, "运营中心", 30),
    (4, "财务中心", 40),
    (5, "人力行政中心", 50),
    (6, "创新业务部", 60),
    (7, "其他部门", 70),
]

CATEGORIES = [
    (1, "产品原型", 1, 10),
    (2, "企业宣传", 1, 20),
]


def seed_data(apps, schema_editor):
    Department = apps.get_model("projects", "Department")
    ProjectCategory = apps.get_model("projects", "ProjectCategory")
    Project = apps.get_model("projects", "Project")

    for department_id, name, sort_order in DEPARTMENTS:
        Department.objects.update_or_create(
            id=department_id,
            defaults={"name": name, "sort_order": sort_order},
        )

    for category_id, name, department_id, sort_order in CATEGORIES:
        ProjectCategory.objects.update_or_create(
            id=category_id,
            defaults={
                "name": name,
                "department_id": department_id,
                "sort_order": sort_order,
            },
        )

    updated_at = timezone.make_aware(datetime(2026, 5, 20, 9, 30))
    project, _created = Project.objects.update_or_create(
        id="99999999",
        defaults={
            "host": "project_center_admin",
            "name": "数字人需求用例",
            "template": "pc",
            "description": "用于管理部门、项目类型和项目模板配置。",
            "prompt": "",
            "department_id": 1,
            "category_id": 1,
            "created_at": updated_at,
            "updated_at": updated_at,
        },
    )
    Project.objects.filter(id=project.id).update(updated_at=updated_at)


def remove_data(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectCategory = apps.get_model("projects", "ProjectCategory")
    Department = apps.get_model("projects", "Department")
    Project.objects.filter(id="99999999").delete()
    ProjectCategory.objects.filter(id__in=[item[0] for item in CATEGORIES]).delete()
    Department.objects.filter(id__in=[item[0] for item in DEPARTMENTS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data, remove_data),
    ]
