# Generated by Codex on 2026-05-21

import uuid
from datetime import datetime

from django.db import migrations
from django.utils import timezone


DEPARTMENTS = [
    ("11111111-1111-4111-8111-111111111111", "产品研发中心", 10),
    ("22222222-2222-4222-8222-222222222222", "教研中心", 20),
    ("33333333-3333-4333-8333-333333333333", "运营中心", 30),
    ("44444444-4444-4444-8444-444444444444", "财务中心", 40),
    ("55555555-5555-4555-8555-555555555555", "人力行政中心", 50),
    ("66666666-6666-4666-8666-666666666666", "创新业务部", 60),
    ("77777777-7777-4777-8777-777777777777", "其他部门", 70),
]

CATEGORIES = [
    (
        "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
        "产品原型",
        "11111111-1111-4111-8111-111111111111",
        10,
    ),
    (
        "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
        "企业宣传",
        "11111111-1111-4111-8111-111111111111",
        20,
    ),
]


def seed_data(apps, schema_editor):
    Department = apps.get_model("projects", "Department")
    ProjectCategory = apps.get_model("projects", "ProjectCategory")
    Project = apps.get_model("projects", "Project")

    for department_id, name, sort_order in DEPARTMENTS:
        Department.objects.update_or_create(
            id=uuid.UUID(department_id),
            defaults={"name": name, "sort_order": sort_order},
        )

    for category_id, name, department_id, sort_order in CATEGORIES:
        ProjectCategory.objects.update_or_create(
            id=uuid.UUID(category_id),
            defaults={
                "name": name,
                "department_id": uuid.UUID(department_id),
                "sort_order": sort_order,
            },
        )

    updated_at = timezone.make_aware(datetime(2026, 5, 20, 9, 30))
    project, _created = Project.objects.update_or_create(
        id=uuid.UUID("99999999-9999-4999-8999-999999999999"),
        defaults={
            "host": "project_center_admin",
            "name": "数字人需求用例",
            "template": "pc",
            "description": "用于管理部门、项目类型和项目模板配置。",
            "prompt": "",
            "department_id": uuid.UUID("11111111-1111-4111-8111-111111111111"),
            "category_id": uuid.UUID("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
            "created_at": updated_at,
            "updated_at": updated_at,
        },
    )
    Project.objects.filter(id=project.id).update(updated_at=updated_at)


def remove_data(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectCategory = apps.get_model("projects", "ProjectCategory")
    Department = apps.get_model("projects", "Department")
    Project.objects.filter(id=uuid.UUID("99999999-9999-4999-8999-999999999999")).delete()
    ProjectCategory.objects.filter(id__in=[uuid.UUID(item[0]) for item in CATEGORIES]).delete()
    Department.objects.filter(id__in=[uuid.UUID(item[0]) for item in DEPARTMENTS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data, remove_data),
    ]
